title: <p align="center"> Chris Tran </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="http://www.linkedin.com/in/chintiaalvina">LinkedIn</a> |
  <a href="https://github.com/chintiaalvn">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursuing Bachelor's degree in Islamic Economics at Faculty of Economics and Business, Universitas Muhammadiyah Prof. Dr. Hamka.
  <br><br>
  I am currently a participant in the Data Analytics Course at Zenius from MSIB Program by Kampus Merdeka.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
